In [66]:
import pandas as pd 

PATHS = {
    'pop_2020': "/Users/romain/Desktop/Projets DS/Python-project/analyse/data/population_2020.CSV",
    'pop_2014': "/Users/romain/Desktop/Projets DS/Python-project/analyse/data/population_2014.xls",
    'diplo_2020': "/Users/romain/Desktop/Projets DS/Python-project/analyse/data/diplome_2020.CSV",
    'diplo_2014': "/Users/romain/Desktop/Projets DS/Python-project/analyse/data/diplome_2014.xls",
    'rev_2019': "/Users/romain/Desktop/Projets DS/Python-project/analyse/data/revenu_2019.csv",
    'rev_2013': "/Users/romain/Desktop/Projets DS/Python-project/analyse/data/revenu_2013.xls"
}

df_pop_2020 = pd.read_csv(PATHS['pop_2020'], sep=';',dtype={'COM':'str'})
df_pop_2014 = pd.read_excel(PATHS['pop_2014'],header=5,dtype={'COM':'str'})
df_diplo_2020 = pd.read_csv(PATHS['diplo_2020'], sep=';',header=0,dtype={'COM':'str'})
df_diplo_2014 = pd.read_excel(PATHS['diplo_2014'],header=5,dtype={'CODGEO':'str'})
df_rev_2019 = pd.read_csv(PATHS['rev_2019'], sep=';',dtype={'CODGEO':'str'})
df_rev_2013 = pd.read_excel(PATHS['rev_2013'],header=5,dtype={'CODGEO':'str'})

/var/folders/47/r5kv9z4j6kg1sk0dvr2l5ydh0000gn/T/ipykernel_75012/864678703.py:12: DtypeWarning: Columns (0,3) have mixed types. Specify dtype option on import or set low_memory=False.
  df_pop_2020 = pd.read_csv(PATHS['pop_2020'], sep=';',dtype={'COM':'str'})
/var/folders/47/r5kv9z4j6kg1sk0dvr2l5ydh0000gn/T/ipykernel_75012/864678703.py:14: DtypeWarning: Columns (0,3) have mixed types. Specify dtype option on import or set low_memory=False.
  df_diplo_2020 = pd.read_csv(PATHS['diplo_2020'], sep=';',header=0,dtype={'COM':'str'})

Fusion en un unqiue .csv de toutes les données explicatives brutes (sans delta). On fera deltaY=delta vote, sur les deltaX.

In [93]:
print("Pop 2014 unique ?", df_pop_2014['COM'].is_unique)
print("Pop 2020 unique ?", df_pop_2020['COM'].is_unique)
print("Diplo 2020 unique ?", df_diplo_2020['COM'].is_unique)
print("Diplo 2014 unique ?", df_diplo_2014['CODGEO'].is_unique)
print("Rev 2013 unique ?", df_rev_2013['CODGEO'].is_unique)
print("Rev 2019 unique ?", df_rev_2019['CODGEO'].is_unique)

Pop 2014 unique ? False
Pop 2020 unique ? False
Diplo 2020 unique ? False
Diplo 2014 unique ? True
Rev 2013 unique ? True
Rev 2019 unique ? True

In [94]:

df_pop_2020=df_pop_2020[['COM','P20_POP','C20_POP15P_CS3']]
df_pop_2014=df_pop_2014[['COM','P14_POP','C14_POP15P_CS3']]
df_pop_2020.head()
df_pop_2014.head()
df_diplo_2014=df_diplo_2014[['CODGEO','P14_NSCOL15P_SUP']]
df_diplo_2020=df_diplo_2020[['COM','P20_NSCOL15P_SUP2','P20_NSCOL15P_SUP34','P20_NSCOL15P_SUP5']]
df_rev_2013=df_rev_2013[['CODGEO','MED13']]
df_rev_2019=df_rev_2019[['CODGEO','MED19']]

In [95]:
print("Pop 2014 unique ?", df_pop_2014['COM'].is_unique)
print("Pop 2020 unique ?", df_pop_2020['COM'].is_unique)
print("Diplo 2020 unique ?", df_diplo_2020['COM'].is_unique)
print("Diplo 2014 unique ?", df_diplo_2014['CODGEO'].is_unique)
print("Rev 2013 unique ?", df_rev_2013['CODGEO'].is_unique)
print("Rev 2019 unique ?", df_rev_2019['CODGEO'].is_unique)

Pop 2014 unique ? False
Pop 2020 unique ? False
Diplo 2020 unique ? False
Diplo 2014 unique ? True
Rev 2013 unique ? True
Rev 2019 unique ? True

Problème de doublons (population par IRIS, même COM, ou alors Hommes vs Femmes...)
Solution: groupby

In [ ]:
df_diplo_2020_test = df_diplo_2020.groupby('COM').sum().reset

In [98]:
df_diplo_2020_test.head()

       P20_NSCOL15P_SUP2  P20_NSCOL15P_SUP34  P20_NSCOL15P_SUP5
COM
01001          83.435537           58.938581          38.706320
01002          28.977294           27.590460          23.934686
01004        1345.650547          800.138921         732.117886
01005         186.000000          104.000000          87.000000
01006          11.894737           10.903509           5.947368

.reset_index() INDISPENSABLE pour remettre l'index et remettre COm en nom de colonne pour jointure

In [ ]:
df_diplo_2020 = df_diplo_2020.groupby('COM').sum().reset_index()
df_pop_2014 = df_pop_2014.groupby('COM').sum().reset_index()
df_pop_2020 = df_pop_2020.groupby('COM').sum().reset_index()

In [102]:
df_pop_2020.head()

     COM  P20_POP  C20_POP15P_CS3
0  01001    806.0       61.774238
1  01002    262.0       18.283656
2  01004  14288.0      804.651500
3  01005   1782.0      115.000000
4  01006    113.0        9.912281

In [107]:
df_2014=pd.merge(df_pop_2014,df_diplo_2014, left_on='COM', right_on='CODGEO', how='left')

In [ ]:
df_2014.head()
df_2014 = df_2014.drop(columns=['CODGEO'])
#df_rev_2013.head()

     COM  P14_POP  C14_POP15P_CS3  P14_NSCOL15P_SUP
0  01001    767.0       75.000000        141.000000
1  01002    239.0       14.753086         59.995885
2  01004  14022.0      743.288479       2326.327150
3  01005   1627.0      105.518839        281.383570
4  01006    109.0        4.954545         12.881818

In [112]:

df_2014=pd.merge(df_2014,df_rev_2013, left_on='COM', right_on='CODGEO', how='left')

In [114]:
df_2014=df_2014.drop(columns=['CODGEO'])

In [115]:
df_2014.head()

     COM  P14_POP  C14_POP15P_CS3  P14_NSCOL15P_SUP         MED13
0  01001    767.0       75.000000        141.000000  22130.000000
1  01002    239.0       14.753086         59.995885  23213.000000
2  01004  14022.0      743.288479       2326.327150  19554.000000
3  01005   1627.0      105.518839        281.383570  22387.619048
4  01006    109.0        4.954545         12.881818  21871.666667

In [77]:
df_rev_2019.head()

  CODGEO  MED19
0  01001  23970
1  01002  23640
2  01004  20510
3  01005  24050
4  01006      s

In [116]:
df_2020=pd.merge(df_pop_2020,df_diplo_2020, left_on='COM', right_on='COM', how='left')

In [117]:
df_2020.head()
df_2020=pd.merge(df_2020,df_rev_2019, left_on='COM', right_on='CODGEO', how='left')

In [ ]:
df_2020.head()
df_2020=df_2020.drop(columns=['CODGEO'])

KeyError: "['CODGEO'] not found in axis"

In [120]:
df_2020.head()

,COM,P20_POP,C20_POP15P_CS3,P20_NSCOL15P_SUP2,P20_NSCOL15P_SUP34,P20_NSCOL15P_SUP5,MED19
0,01001,806.0,61.774238,83.435537,58.938581,38.706320,23970
1,01002,262.0,18.283656,28.977294,27.590460,23.934686,23640
2,01004,14288.0,804.651500,1345.650547,800.138921,732.117886,20510
3,01005,1782.0,115.000000,186.000000,104.000000,87.000000,24050
4,01006,113.0,9.912281,11.894737,10.903509,5.947368,s

In [121]:
df=pd.merge(df_2014,df_2020, left_on='COM', right_on='COM', how='left')

In [122]:
df.head(100)

,COM,P14_POP,C14_POP15P_CS3,P14_NSCOL15P_SUP,MED13,P20_POP,C20_POP15P_CS3,P20_NSCOL15P_SUP2,P20_NSCOL15P_SUP34,P20_NSCOL15P_SUP5,MED19
0,01001,767.0,75.000000,141.000000,22130.000000,806.0,61.774238,83.435537,58.938581,38.706320,23970
1,01002,239.0,14.753086,59.995885,23213.000000,262.0,18.283656,28.977294,27.590460,23.934686,23640
2,01004,14022.0,743.288479,2326.327150,19554.000000,14288.0,804.651500,1345.650547,800.138921,732.117886,20510
3,01005,1627.0,105.518839,281.383570,22387.619048,1782.0,115.000000,186.000000,104.000000,87.000000,24050
4,01006,109.0,4.954545,12.881818,21871.666667,113.0,9.912281,11.894737,10.903509,5.947368,s
...,...,...,...,...,...,...,...,...,...,...,...
95,01103,1459.0,193.000000,449.000000,36382.000000,2226.0,335.743069,187.194660,227.757010,324.653800,40750
96,01104,461.0,10.021739,95.206522,22047.200000,453.0,32.190995,49.036584,38.875977,30.720273,25530
97,01105,1489.0,170.000000,347.000000,25740.400000,1867.0,204.156572,232.720261,150.055711,154.126633,27000
98,01106,173.0,5.000000,24.000000,19107.500000,178.0,4.972067,15.910615,8.949721,3.977654,22170
99,01107,136.0,10.074074,31.229630,21548.000000,136.0,18.888889,11.333333,17.944444,7.555556,22050

In [123]:
# Chemin de sortie
output_path = '/Users/romain/Desktop/Projets DS/Python-project/analyse/fusion_data.csv'

# L'exportation propre
df.to_csv(
    output_path, 
    index=False,   # CRUCIAL : Ne pas enregistrer la colonne d'index (0, 1, 2...)
    na_rep='NA',   # CRUCIAL POUR R : Remplacer les vides par "NA"
    sep=',',       # Standard international (virgule)
    encoding='utf-8'
)

print(f"Exporté avec succès vers : {output_path}")

Exporté avec succès vers : /Users/romain/Desktop/Projets DS/Python-project/analyse/fusion_data.csv

In [11]:
import pandas as pd 

df_elec_2014 = pd.read_csv('/Users/romain/Desktop/Projets DS/Python-project/analyse/data/elec_2014.csv', dtype={'Code commune':'str'})
df_elec_2020 = pd.read_csv('/Users/romain/Desktop/Projets DS/Python-project/analyse/data/elec_2020.csv', dtype={'Code commune':'str'})

df_elec_2014 = df_elec_2014.rename(columns={'Code commune':'COM','D_elec_2020':'D_elec_2014','Code Nuance':'Code Nuance 2014'})
df_elec_2020 = df_elec_2020.rename(columns={'Code commune':'COM','Nuance Liste':'Code Nuance 2020'})

In [12]:

df_elec_2014 = df_elec_2014[ ['COM','Code Nuance 2014','D_elec_2014'] ]
df_elec_2020 = df_elec_2020[ ['COM','Code Nuance 2020','D_elec_2020'] ]

In [ ]:
df_variables = pd.read_csv("/Users/romain/Desktop/Projets DS/Python-project/analyse/fusion_data.csv", dtype={'COM':'str'})

     COM Code Nuance 2014  D_elec_2014
0  01004             LDVD          0.0
1  01007             LDVG          1.0
2  01034             LDVD          0.0
3  01160             LDVD          0.0
4  01185             LUDI          0.0